ARG BASE_IMAGE=ros:humble
FROM $BASE_IMAGE

ARG USERNAME
ARG USER_UID
ARG USER_GID
ARG TARGET_PLATFORM
ENV USER=${USERNAME}
ENV TARGET_PLATFORM=${TARGET_PLATFORM}

# Delete user if it exists in container
RUN if id -u $USER_UID ; then userdel `id -un $USER_UID` ; fi

# Needed setup dependencies (no update to fix base source lists)
RUN apt-get install -y --no-install-recommends \
        curl gnupg2 ca-certificates sudo

# Ensure ROS package list available
RUN set -eux; \
    if ! apt-get update -y; then \
        rm -f /etc/apt/sources.list.d/ros2-latest.list /usr/share/keyrings/ros-archive-keyring.gpg; \
        curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
            | gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg; \
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu jammy main" \
            > /etc/apt/sources.list.d/ros2.list; \
        apt-get update -y; \
    fi

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# Prepare installation and work environment
WORKDIR /home/${USERNAME}/robosub_ws
COPY requirements.txt .
COPY apt-packages.txt .
COPY package-ignore.txt .

# Install dependencies
RUN apt-get update && apt-get upgrade -y && apt-get install -y python3-pip python3-venv build-essential \
    && grep -vFf package-ignore.txt apt-packages.txt | xargs apt-get -y -o Dpkg::Options::="--force-overwrite" install --no-install-recommends \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Virtualize and install Python packages
COPY pip.conf /etc/pip.conf
ENV PIP_INDEX_URL=""
ENV PIP_EXTRA_INDEX_URL=""
RUN python3 -m venv --system-site-packages /workspace/venv \
    && /workspace/venv/bin/pip install --upgrade pip \
    && /workspace/venv/bin/pip install --no-cache-dir -r requirements.txt
ENV PATH=/workspace/venv/bin:$PATH

# Startup setup
RUN chown -R $USER:$USER /workspace/venv 
RUN usermod -aG video,dialout $USERNAME
USER $USERNAME
ENV SHELL=/bin/bash
CMD ["/bin/bash"]
