services:
  dev:
    image: lunarzdev/mhseals-dev:jetson
    build:
      args:
        TARGET_PLATFORM: jetson
        BASE_IMAGE: dustynv/ros:humble-desktop-l4t-r36.4.0
    runtime: nvidia
    volumes:
      - zed_resources:/usr/local/zed/resources 
      - /tmp/argus_socket:/tmp/argus_socket
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      EGL_PLATFORM: surfaceless
      XDG_RUNTIME_DIR: /tmp/runtime-roboboat
      QT_QPA_PLATFORM: offscreen
  sitl:
    image: lunarzdev/mhseals-dev:jetson
    volumes:
      - ./boat.param:/param/boat.param:rw
volumes:
  zed_resources:
